# Generated by Django 5.0.6 on 2024-08-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='back_side_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='front_side_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
