# Generated by Django 5.0.6 on 2024-08-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_back_side_image_url_order_front_side_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='back_side_image_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='front_side_image_url',
        ),
    ]
