# Generated by Django 5.0.6 on 2024-08-21 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_back_side_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, help_text='If you provide an email address, a link to the order details will be sent to your email.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be a 10-digit number without leading zeros', regex='^[1-9][0-9]{9}$')]),
        ),
    ]
